config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :contacts, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'create', to: 'contacts#create'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get "songs", to: "songs#index"
  get "songs/new", to: "songs#new"
  get "songs/list", to: "songs#list"
  get "gallery", to: "pages#gallery"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :venue,     :validate => true
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Alexandra Lansdale - Wedding Singer Email",
      :to => "gareth@caryfamily.co.uk",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/song.rb
class Song < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def list
    @songs = Song.where(genre: params.dig(:search, :genre))
    @songs = Song.all if @songs.empty?
  end


  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new # needed to instantiate the form_for
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/contacts/create.html.erb
<%= render "pages/navbar1" %>

<div class="create-page-content">
  <div class="create-page-info">
    <h1>Thank you for getting in contact</h1>
    <br>
    <h2>We will respond as soon as possible</h2>
    <br>
    <br>
    <%= link_to "Finish", root_path, class: 'link-back-home' %>
  </div>
</div>

<%= render "pages/footer1" %>

app/views/contacts/new.html.erb
<%= render "pages/navbar1" %>


<div class="contact-page-wrapping-whole-content">
  <h1 id="page_title">Contact</h1>

  <div class="contact-form-contact-new">
    <div>
      <%= form_for @contact do |f| %>

      <%= f.label :name, class: 'label_contact' %><br>
      <%= f.text_field :name, required: true, class: 'text_area_contact' %>

      <br>

      <%= f.label :email, class: 'label_contact' %><br>
      <%= f.email_field :email, required: true, class: 'text_area_contact' %>

      <br>

      <%= f.label :venue, class: 'label_contact' %><br>
      <%= f.text_field :venue, required: true, class: 'text_area_contact' %>

      <br>

      <%= f.label :message, class: 'label_contact' %><br>
      <%= f.text_area :message, as: :text, class: 'message_area_contact' %>

      <div class="hidden">
        <%= f.label :nickname %><br>
        <%= f.text_field :nickname, hint: 'leave this field blank' %>
      </div>

      <br>
      <br>

      <%= f.submit 'Send Message', class: 'button_contact' %>

      <% end %>



    </div>
  </div>
</div>

<br>

<br>

<br>

<br>

<br>


<%= render "pages/footer1" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wedding Singer Alexandra Lansdale</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path('favicon.png') %>

  </head>

  <body>

    <%= yield %>



        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
       <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/_footer.html.erb
<div class="footer1">
  <div>
    <%= image_tag "logo-home-page-2.png", class: "footer-logo" %>
  </div>
  <div>
    <h3>Email:</h3>
    <%= mail_to("alexlansdale1@gmail.com", name = "alexlansdale1@gmail.com", class: "button2") %>
    <br>
    <br>
    <h3>Phone:</h3>
    <p> +44 7983 945 508</p>
    <br>
    <p><i class="fa fa-copyright"></i> Gareth Cary</p>
  </div>
</div>

app/views/pages/_footer1.html.erb
<div class="footer2">
  <div>
    <%= image_tag "logo-home-page-2.png", class: "footer-logo1" %>
  </div>
   <div>
     <h3>Email:</h3>
      <%= mail_to("alexlansdale1@gmail.com", name = "alexlansdale1@gmail.com", class: "button2") %>
    </div>
    <div>
      <h3>Phone:</h3>
      <p> +44 7983 945 508</p>
    </div>
    <div>
      <p><i class="fa fa-copyright"></i> Gareth Cary</p>
    </div>
  </div>
</div>

app/views/pages/_navbar.html.erb
<div class="topnav">
    <%= link_to "Home", root_path %>
    <%= link_to "Songs", songs_list_path %>
    <%= link_to "Gallery", gallery_path %>
    <%= link_to "Contact", new_contact_path %>
    <a href="https://www.facebook.com/Alexandra-Lansdale-Wedding-Singer-106306027697074/?modal=admin_todo_tour" target="#">Follow us <i class="fa fa-facebook-square"></i></a>
  </div>

app/views/pages/_navbar1.html.erb
<div class="nav-bar-home-page">
    <%= link_to "Home", root_path %>
    <%= link_to "Songs", songs_list_path %>
    <%= link_to "Gallery", gallery_path %>
    <%= link_to "Contact", new_contact_path %>
    <a href="https://www.facebook.com/Alexandra-Lansdale-Wedding-Singer-106306027697074/?modal=admin_todo_tour" target="#">Follow us <i class="fa fa-facebook-square"></i></a>
  </div>

app/views/pages/gallery.html.erb
<%= render "pages/navbar" %>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="margin-left-right">
  <div class="row margin-navbar-top">
    <div class="col-lg-4 padding-image-gallery">
      <%= image_tag ("kate2.png"), style: "width: 100%", class: "image-box-shadow" %>
      <%= image_tag ("kate3.png"), style: "width: 100%", class: "image-box-shadow" %>
    </div>
    <div class="col-lg-4 padding-image-gallery">
       <%= image_tag ("kate5.png"), style: "width: 100%", class: "image-box-shadow" %>
        <%= image_tag ("kate4.png"), style: "width: 100%", class: "image-box-shadow" %>
    </div>
    <div class="col-lg-4 padding-image-gallery">
       <%= image_tag ("kate6.png"), style: "width: 100%", class: "image-box-shadow" %>
        <%= image_tag ("kate7.png"), style: "width: 100%", class: "image-box-shadow" %>
    </div>
  </div>
</div>
<br>
<br>

<%= render "footer" %>

app/views/pages/home.html.erb
<%= render "navbar1" %>

<div class="banner-home-page">
  <div class="title-home-page">
    <%= image_tag "logo-home-page-2.png" %>
    <p><em>Wedding Singer at the click of a button</em></p>
  </div>
  <div class="button-home-page">
    <%= link_to "Book Now", new_contact_path, class: 'button-home' %>
  </div>
</div>

<div class="about-title">
  <h1>About - Alexandra</h1>
</div>

<div class="container margin-bottom-home">
  <div class="row margin-top-info">
   <div class="col-lg-4">
      <%= image_tag ("kate7.png"), class: "home-page-image" %>
   </div>
    <div class="col-lg-8 about-info-home-page">
      <h2>Singing range</h3>
      <br>
      <p class="soprano"><em>Soprano and Mezzo-Soprano</em></p>
      <br>
      <h2>Training & Experience</h2>
      <br>
      <p>Alex is a multi-instrumentalist and fully-trained vocalist, who graduated from the University of York in 2017. During her time at University, she performed in several musicals and operas, and sang with many different choirs.</p>
      <p>Whilst Alex began her training as a classical singer, she also trained as a musical theatre vocalist, and so offers a very versatile service in performing whatever is required. Prior to her training, she toured, competed and performed nationally and internationally with the Cantamus Girls’ Choir since the age of 13. This work took her to Malaysia, Singapore, Germany, Austria and Ireland.</p>
      <p>Alex understands the true importance of a wedding day, and prides herself on working closely with clients to provide them with a bespoke and unique service.</p>
    </div>
  </div>
</div>


  <br>
<div style="background-color: lightgrey; margin-right: 30px; margin-left: 30px;">
  <br>
  <h2 style="font-size: 45px; text-align: center; font-family: 'Roboto Slab', serif;">Audio Clips</h2>
  <br>
    <br>
      <br>
<div class="stuff">
  <div class="audio-all-files">
    <div class="audio-file">
      <h3 style="font-family: 'Roboto Slab', serif;">Genre: <em>Contempory</em></h3>
      <h4 style="font-family: 'Roboto Slab', serif;">Song: <em>Fly Me To The Moon</em></h4>
      <p style="font-family: 'Roboto Slab', serif;">Frank Sinatra</p>
      <audio class="audios" id="yes-audio" controls preload="yes-audio">
       <source src="audios/audiofile.mp3" type="audio/mpeg">
      </audio>
    </div>
    <br>
      <br>

    <div class="audio-file">
     <h3 style="font-family: 'Roboto Slab', serif;">Genre: <em>Contempory</em></h3>
      <h4 style="font-family: 'Roboto Slab', serif;">Song: <em>Make You Feel My Love</em></h4>
      <p style="font-family: 'Roboto Slab', serif;">Adele</p>
      <audio class="audios" id="yes-audio" controls preload="yes-audio">
         <source src="audios/makeyoufeelmylove.mp3" type="audio/mpeg">
      </audio>
    </div>
      <br>
        <br>

    <div class="audio-file">
     <h3 style="font-family: 'Roboto Slab', serif;">Genre: <em>Classical</em></h3>
      <h4 style="font-family: 'Roboto Slab', serif;">Song: <em>O Mio Babbino, Caro</em></h4>
      <p style="font-family: 'Roboto Slab', serif;">Giacomo Puccini</p>
      <audio class="audios" id="yes-audio" controls preload="yes-audio">
         <source src="audios/omiobeabbinocaro.mp3" type="audio/mpeg">
      </audio>
    </div>
      <br>
        <br>

    <div class="audio-file">
     <h3 style="font-family: 'Roboto Slab', serif;">Genre: <em>Classical</em></h3>
      <h4 style="font-family: 'Roboto Slab', serif;">Song: <em>Be Thou My Vision</em></h4>
      <p style="font-family: 'Roboto Slab', serif;">Traditional Hymn</p>
      <audio class="audios" id="yes-audio" controls preload="yes-audio">
         <source src="audios/bethoumyvision.mp3" type="audio/mpeg">
      </audio>
    </div>

  </div>
    <br>
      <br>
        <br>
          <br>

</div>
</div>

<%= render "footer" %>

app/views/songs/list.html.erb
<%= render "pages/navbar1" %>

<div class="form-position">
  <div class="banner-song-page">
    <h1>Alexandra Lansdale - Song List</h1>
    <p style="color: white;"><em>Here is a selection of songs from Alex's repertoire.</em></p>
    <p style="color: white;"><em>If you want any other song requests that aren't on the list, please don't hesitate to ask.</em></p>
    <br>
    <div class="button-home-page-margin"><%= link_to "Book Now", new_contact_path, class: "button-song-page" %></div>
   <div class="form_index">
    </div>
       <div class="in-line">
        <%= simple_form_for :search, url: songs_list_path, method: :get do |f| %>
        <%= f.input_field :genre, collection: ["Folk", "Contempory", "Classical", "All"], required: false, input_html: { class: "form_input" } %>
        <%= f.submit "Search", class: "button-list-page"%>
      <% end %>
      </div>
  </div>
</div>

<div class="items">
  <div class="row-of-items">
      <% @songs.each do |song| %>
      <div class="card-product">
        <img src=" <%= song.image %>", alt="Book Club photos" />
        <div class="card-product-infos">
          <h3>Genre:  <em><%= "#{song.genre}" %></em></h3>
          <h4>Song:  <em> <%= "#{song.name}" %></em></h4>
          <p><%= "#{song.artist}" %></p>
        </div>
      </div>
      <% end %>
  </div>

</div>
<br>
<br>
<br>

<%= render "pages/footer" %>